version: "3.8"
name: "aims"
services:
  api-gateway:
    build: .
    image: aims_api_gateway
    container_name: api_gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=dev
      - PORT=3000
